## Problem 2 workings

In [1]:
import torch

def trans_conv(Y, w, b):
    c_in, c_out , f1, f2 = w.shape
    batch, c_in, m, n = Y.shape
    X = torch.zeros(batch, c_out, m+f1-1, n+f2-1)
    for k in range(c_in):
        for i in range(Y.shape[2]):
            for j in range(Y.shape[3]):
                X[:,:,i:i+f1,j:j+f2] += Y[:,k,i,j].view(-1,1,1,1)*w[k, :, :, :].unsqueeze(0)
    return X + b.view(1,-1,1,1)

In [2]:
in_channels = 2

In [3]:
input = torch.arange(1, in_channels**3+1, dtype=torch. float32).view(1, in_channels, in_channels, in_channels)
input

tensor([[[[1., 2.],
          [3., 4.]],

         [[5., 6.],
          [7., 8.]]]])

In [4]:
from torch import nn

r = 3
layer_up = nn.Upsample(scale_factor=r, mode='nearest')

In [5]:
layer_up(input)

tensor([[[[1., 1., 1., 2., 2., 2.],
          [1., 1., 1., 2., 2., 2.],
          [1., 1., 1., 2., 2., 2.],
          [3., 3., 3., 4., 4., 4.],
          [3., 3., 3., 4., 4., 4.],
          [3., 3., 3., 4., 4., 4.]],

         [[5., 5., 5., 6., 6., 6.],
          [5., 5., 5., 6., 6., 6.],
          [5., 5., 5., 6., 6., 6.],
          [7., 7., 7., 8., 8., 8.],
          [7., 7., 7., 8., 8., 8.],
          [7., 7., 7., 8., 8., 8.]]]])

In [6]:
conv_layer = nn.ConvTranspose2d(in_channels, in_channels, r, stride=r, bias=False)
conv_layer.weight.data = torch.zeros(size=(in_channels,in_channels,r,r))
for i in range(in_channels):
    for h in range(r):
        for w in range(r):
            conv_layer.weight.data[i, i, h, w] = 1

conv_layer(input)

tensor([[[[1., 1., 1., 2., 2., 2.],
          [1., 1., 1., 2., 2., 2.],
          [1., 1., 1., 2., 2., 2.],
          [3., 3., 3., 4., 4., 4.],
          [3., 3., 3., 4., 4., 4.],
          [3., 3., 3., 4., 4., 4.]],

         [[5., 5., 5., 6., 6., 6.],
          [5., 5., 5., 6., 6., 6.],
          [5., 5., 5., 6., 6., 6.],
          [7., 7., 7., 8., 8., 8.],
          [7., 7., 7., 8., 8., 8.],
          [7., 7., 7., 8., 8., 8.]]]], grad_fn=<ConvolutionBackward0>)

In [7]:
conv_layer.weight.data

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [8]:
torch.eye(in_channels).unsqueeze(-1).unsqueeze(-1) * torch.ones(1, 1, r, r)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [9]:
torch.eye(in_channels).unsqueeze(-1).unsqueeze(-1)

tensor([[[[1.]],

         [[0.]]],


        [[[0.]],

         [[1.]]]])

In [10]:
torch.eye(in_channels)

tensor([[1., 0.],
        [0., 1.]])

In [11]:
torch.ones(1, 1, r, r)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [24]:
input = torch.arange(1, 5, dtype=torch. float32).view(1, 1, 2, 2)
input

tensor([[[[1., 2.],
          [3., 4.]]]])

In [25]:
layer = nn.ConvTranspose2d(1, 1, kernel_size=r, stride =r, bias = False)
layer.weight.data = torch.ones(1,1,r,r)
layer(input)

tensor([[[[1., 1., 1., 2., 2., 2.],
          [1., 1., 1., 2., 2., 2.],
          [1., 1., 1., 2., 2., 2.],
          [3., 3., 3., 4., 4., 4.],
          [3., 3., 3., 4., 4., 4.],
          [3., 3., 3., 4., 4., 4.]]]], grad_fn=<ConvolutionBackward0>)

## Problem 6 workings

In [1]:
def perform_permutation(l, sig):
    output = [0 for _ in range(len(l))]
    for i in range(len(l)):
        output[i] = l[sig[i]]
    return output

In [3]:
import random
base_list = [i for i in range(10)]
random.shuffle(base_list)

sigma = base_list.copy()
random.shuffle(sigma)

permuted_list = perform_permutation(base_list, sigma)
base_list, sigma, permuted_list

([2, 9, 6, 1, 5, 8, 3, 7, 4, 0],
 [1, 0, 6, 5, 4, 3, 2, 7, 9, 8],
 [9, 2, 3, 8, 5, 1, 6, 7, 0, 4])

In [4]:
def inverse_permutation(sig):
    output = [0 for _ in range(len(sig))]
    pos = 0
    for s in sig:
        output[s] = pos
        pos += 1
    return output

In [5]:
sigma_inverse = inverse_permutation(sigma)
permuted_list, sigma_inverse, perform_permutation(permuted_list, sigma_inverse)

([9, 2, 3, 8, 5, 1, 6, 7, 0, 4],
 [1, 0, 6, 5, 4, 3, 2, 7, 9, 8],
 [2, 9, 6, 1, 5, 8, 3, 7, 4, 0])

In [6]:
perform_permutation(permuted_list, sigma_inverse) == base_list

True